name: Deployer CI

env:
  CI: true

on:
  push:
    branches: "*"
    paths:
      - packages/deployer/**
  pull_request:
    branches: "*"
    paths:
      - packages/deployer/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn workspace @mimic-fi/v3-deployer lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Test
        run: yarn workspace @mimic-fi/v3-deployer test
