name: Relayer CI

env:
  CI: true

on:
  push:
    branches: "*"
    paths:
      - packages/relayer/**
  pull_request:
    branches: "*"
    paths:
      - packages/relayer/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn workspace @mimic-fi/v3-relayer lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Test
        run: yarn workspace @mimic-fi/v3-relayer test
